name: Android CI for DroidVim

on:
  push:
    branches:
      - main
      - build
      - 'releases/**'
  pull_request:
    branches: [ "main", "build" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload droidvim flavor APK
      uses: actions/upload-artifact@v4
      with:
        name: term-droidvim-release.apk
        path: ./term/build/outputs/apk/droidvim/release/term-droidvim-release-unsigned.apk

    - name: Upload terminal flavor APK
      uses: actions/upload-artifact@v4
      with:
        name: term-terminal-release.apk
        path: ./term/build/outputs/apk/terminal/release/term-terminal-release-unsigned.apk
